#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

define('DS', DIRECTORY_SEPARATOR);
define('ROOT', __DIR__);

// Load environment variables
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

// Load configuration files
foreach (glob(ROOT . DS . 'config' . DS . '*.php') as $configFile) {
    require_once $configFile;
}

// Initialize Symfony Console application
$app = new Application();

// Dynamically load and add command classes
$commandNamespace = 'Console\\Commands';
$commandDir = ROOT . DS . 'src' . DS . 'Console' . DS . 'Commands';

foreach (glob($commandDir . DS . '*.php') as $commandFile) {
    $commandClass = $commandNamespace . '\\' . pathinfo($commandFile, PATHINFO_FILENAME);
    if (class_exists($commandClass)) {
        $app->add(new $commandClass());
    }
}

$app->run();
