#!/user/bin/env php
<?php

//define('CONSOLE_ROOT', __DIR__);
//define('DS', DIRECTORY_SEPARATOR);

include ('src/init/setup-composer.php');
echo "------------------------------------------------------------";
include ('console');
echo "Setting up  console";
echo "------------------------------------------------------------";
exec('php console hello-world');